# Generated by Django 5.2.5 on 2026-08-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='task',
            field=models.CharField(default=1, verbose_name='خدمات اریه شده در پروژه'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ServiceTask',
        ),
    ]
