# Generated by Django 5.2.5 on 2026-08-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_service_slug_service_task_delete_servicetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default=1, upload_to='images/services'),
            preserve_default=False,
        ),
    ]
