# Generated by Django 5.2.5 on 2026-08-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_contactus_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_experience', models.PositiveIntegerField(verbose_name='سال تجربه')),
                ('happy_clients', models.PositiveIntegerField(verbose_name='مشتریان راضی')),
                ('service_hours', models.PositiveIntegerField(verbose_name='ساعت خدمات')),
                ('successful_projects', models.PositiveIntegerField(blank=True, null=True, verbose_name='پروژه موفق')),
            ],
        ),
    ]
