# Generated by Django 5.2.5 on 2026-08-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_companystats'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('job', models.CharField(max_length=100, verbose_name='سمت')),
                ('image', models.ImageField(upload_to='images/team', verbose_name='تصویر ')),
                ('inestagram', models.URLField(blank=True, verbose_name='اینستاگرام')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='لینکدین')),
                ('twitter_url', models.URLField(blank=True, verbose_name='توییتر')),
            ],
            options={
                'verbose_name': 'اعضای تیم',
            },
        ),
    ]
