# Generated by Django 5.2.5 on 2026-08-23 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_teammember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={},
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='inestagram',
            new_name='instagram',
        ),
    ]
