# Generated by Django 5.2.5 on 2026-08-22 20:36

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_experience', models.PositiveIntegerField(verbose_name='سال تجربه')),
                ('happy_clients', models.PositiveIntegerField(verbose_name='مشتریان راضی')),
                ('service_hours', models.PositiveIntegerField(verbose_name='ساعت خدمات')),
                ('successful_projects', models.PositiveIntegerField(blank=True, null=True, verbose_name='پروژه موفق')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600, verbose_name='عنوان پروژه')),
                ('image', models.ImageField(upload_to='images/Projects', verbose_name='تصویر')),
                ('project_type', models.CharField(max_length=100, verbose_name='نوع پروژه')),
                ('start_time', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع پروژه')),
                ('end_time', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ پایان پروژه')),
                ('status', models.CharField(choices=[('پایان یافته', 'پایان یافته'), ('در حال اجرا', 'در حال اجرا'), ('در انتظار اجرا', 'در انتظار اجرا')], max_length=20, verbose_name='وضعیت')),
                ('about', models.TextField(verbose_name='درباره پروژه')),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
