# Generated by Django 5.2.5 on 2026-08-22 04:39

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600, verbose_name='عنوان پروژه')),
                ('type', models.CharField(max_length=100, verbose_name='نوع پروژه')),
                ('start_time', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع پروژه')),
                ('end_time', django_jalali.db.models.jDateField(verbose_name='تاریخ پایان پروژه')),
                ('status', models.CharField(choices=[('completed', 'پایان یافته'), ('in_progress', 'در حال اجرا'), ('pending', 'در انتظار اجرا')], max_length=20, verbose_name='وضعیت')),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True)),
            ],
        ),
    ]
