# Generated by Django 5.2.5 on 2026-08-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=None, upload_to='images/Projects', verbose_name='تصویر'),
            preserve_default=False,
        ),
    ]
