# Generated by Django 5.2.5 on 2026-08-22 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyStats',
        ),
    ]
