# Generated by Django 5.2.5 on 2026-08-22 05:12

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_project_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_time',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ پایان پروژه'),
        ),
    ]
